Added root check to the control script.

diff --git a/clashctl b/clashctl
--- a/clashctl
+++ b/clashctl
@@ -12,6 +12,12 @@ GEOSITE_FILE="${CLASH_ETC}/GeoSite.dat"
 GEOIP_URL="https://cdn.jsdelivr.net/gh/Cornfy/geoip@release/geoip-asn.dat"
 GEOSITE_URL="https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
 
+# Check if you are running as root
+if [[ $EUID -ne 0 ]]; then
+    echo "ERROR: Please run this script as root."
+    exit 1
+fi
+
 # Function to handle errors and exit
 handleError()
 {
